# Site Settings
title: "Home"
description: "Forensic Engineer and Curious Human"
url: "https://charlesbwhetstone.github.io"
baseurl: ""
locale: "en-US"
repository: "charlesbwhetstone/charlesbwhetstone.github.io"

# Theme Configuration
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "dark"

# Site Author
author:
  name: "Charles Whetstone"
  bio: "Forensic Engineer and forever a curious human who loves to gain insights from the blob of data as we know it and passionate about building meaningful connections while discovering the unknown. *'Your scientists were so preoccupied with whether or not they could, they didn't stop to think if they should.'* - Jurassic Park"
  location: "United States"
  email: "charlesbwhetstone@icloud.com"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/charlesbwhetstone"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/charlesbwhetstone"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:charlesbwhetstone@icloud.com"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
paginate: 5
paginate_path: /blog/page:num/
future: false

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Search
search: true

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
  - scope:
      path: "_projects"
      type: projects
    values:
      layout: single
      author_profile: true
      share: true
      sidebar:
        nav: "projects"
