# Site Settings - Updated Sep 17, 2025 - Minimal config for testing
title: "Home"
description: "Forensic Engineer and Curious Human"
url: "https://charlesbwhetstone.github.io"
baseurl: ""

# Theme Configuration
theme: minima

# Site Author
author:
  name: "Charles Whetstone"
  bio: "Curious Human"

# Build settings
markdown: kramdown

# Plugins
plugins:
  - jekyll-feed
