# Site Settings
title: "Home"
description: "Forensic Engineer and Curious Human"
url: "https://charlesbwhetstone.github.io"
baseurl: ""
repository: "charlesbwhetstone/charlesbwhetstone.github.io"

# Theme Configuration  
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"

# Site Author
author:
  name: "Charles Whetstone"
  bio: "Curious Human"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/charlesbwhetstone"

# Build settings
markdown: kramdown
plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
